services:
  web:
    build:
      context: .
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000/api
    volumes:
      - .:/app
    command: npm run dev -- --host