services:
  web:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000/api
    command: npm run dev -- --port 3000 --host
    tty: true