server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location /assets/ {
    try_files $uri =404;
    access_log off;
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  location = /env.json {
    try_files $uri =404;
    access_log off;
    expires off;
    add_header Cache-Control "no-store" always;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
